
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ny_taxi_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ny_taxi_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ny_taxi_dbt:
    staging:
      +schema: ny_taxi_staging
      +materialized: view

    marts:
      +schema: ny_taxi_marts
      +materialized: table

seeds:
  ny_taxi_dbt:
    reference:
      +schema: ny_taxi_raw
      +quote_columns: false
